##Server: OK
GET http://localhost:5000/

# <================= AUTH =================>
### Register user: OK
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thang",
    "password": "123456",
    "email": "thang@gmail.com",
    "fullname": "Thang Dao"
}
### Register admin: OK
POST  http://localhost:5000/api/auth/register/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4MjMxZTI2OGRhNTU0ZGY0NjllYTAiLCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNjU4OTQxMDM2fQ.yUSMP-M9iZ6FucHwnb6d9jW2fibmN9d-2yPRbYBJG1E

{
    "username": "admin6",
    "password": "123456",
    "email": "admin6@gmail.com",
    "fullname": "Admin6"
}
### LOGIN user : OK
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "thang",
    "password": "123456"
}
### Login admin: OK
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}
### Get all users: OK
GET http://localhost:5000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4MjMxZTI2OGRhNTU0ZGY0NjllYTAiLCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNjU4OTQxMDM2fQ.yUSMP-M9iZ6FucHwnb6d9jW2fibmN9d-2yPRbYBJG1E

### Get user by id: OK
GET http://localhost:5000/api/user/62efd37dd029bcd07b10cd5b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTE2ZTc4OTMxNWI2Mzk5Nzc0NWRhYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTg4NTQ2MSwiZXhwIjoxNjYwNDkwMjYxfQ.li7pOvvww2rC0biid9Nwzj3fN_S2aBHelObpbEOI84c

###update user: OK
PUT http://localhost:5000/api/user/62ca78b157f1bc0d5fc6c65e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDU2MTdmODRjYThjMDM4ZWUxZDYwOCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU5ODQxMDMxLCJleHAiOjE2NjA0NDU4MzF9.f77j6izcXM5kPqEA8nCTM0BcsjKYSQD8Sh2c1VorT1c

{
    "password": "123456",
    "email": "EMAIL3"
}

### DELETE user: OK
DELETE  http://localhost:5000/api/user/62d66381b5a453632bb220ce
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjRiMmQ1ZWQ5YTg1NmMzMTFiNjkzZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MDIyNzMxMiwiZXhwIjoxNjYwODMyMTEyfQ.L7saLsHkimgcqrkUa11MEoxqRgoPeTuXc1d46jPdN5g
# <============ ARTICLE ==============>

### Create article w/ richtext editor and img: DOING
POST http://localhost:5000/api/article/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDgyNTI5Y2ViYzY3MWNkMDg0Nzk1YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU5ODYxMzc2LCJleHAiOjE2NjA0NjYxNzZ9.sOzGZsf4F0XFgJ-K9uPxYISd84clL95US3xqffLzLZc
Content-Type: application/json

{
    "title": "Núi lửa   triệu atấn nước lên khí quyển",
    "author": "PH",
    "content": "qwdssqwdq qwdqw dqwd qwdqwd qwdqwdqdqwdqwd font-semibold leading-tight md:text-lg md:leading-tight md:tracking-tight font-semibold leading-tight md:text-lg md:leading-tight md:tracking-tightfont-semibold leading-tight md:text-lg md:leading-tight md:tracking-tight",
    "category": ["Khoa học", "Tech"]

}
### create category: OK
POST http://localhost:5000/api/category/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDgyNTI5Y2ViYzY3MWNkMDg0Nzk1YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU5ODYxMzc2LCJleHAiOjE2NjA0NjYxNzZ9.sOzGZsf4F0XFgJ-K9uPxYISd84clL95US3xqffLzLZc

{
    "name": ""
}
### GET ALL Article : OK
GET http://localhost:5000/api/article/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjRiMmQ1ZWQ5YTg1NmMzMTFiNjkzZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MDIyNzMxMiwiZXhwIjoxNjYwODMyMTEyfQ.L7saLsHkimgcqrkUa11MEoxqRgoPeTuXc1d46jPdN5g
### GET ALL Article BY Author: OK
GET http://localhost:5000/api/article?author=ACsS

### GET ALL Article BY Cats: OK
GET http://localhost:5000/api/article?category=Blockchain

### GET article detail BY slug: OK
GET http://localhost:5000/api/article/article-asdsada-awe1-sda

### GET article detail BY id: OK
GET http://localhost:5000/api/article/id/62ebb84c78ee3407d373e975

### Search article by title: OK
GET http://localhost:5000/api/article/search?query=draff

### GET Top article: 
GET http://localhost:5000/api/article/top

### Update article: OK
PUT http://localhost:5000/api/article/62ef7883501ec117262db2cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDgyNTI5Y2ViYzY3MWNkMDg0Nzk1YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU5ODYxMzc2LCJleHAiOjE2NjA0NjYxNzZ9.sOzGZsf4F0XFgJ-K9uPxYISd84clL95US3xqffLzLZc
Content-Type: application/json

{
    "title": "Núi lửa phun tarào ở Tong bắn 146 triệu tấn nước lên khí quyển",
    "author": "update autho2r",
    "content": "Núi lửa phun trào Núi lửa phun trào ở Tonga bắn 146 triệu tấn nước lên khí quyểnNúi lửa phun trào ở Tonga bắn 146 triệu tấn nước lên khí quyểnNúi lửa phun trào ở Tonga bắn 146 triệu tấn nước lên khí quyểnở Tonga bắn 146 triệu tấn nước lên khí quyển Núi lửa phun trào ở Tonga bắn 146 triệu tấn nước lên khí quyểnNúi lửa phun trào ở Tonga bắn 146 triệu tấn nước lên khí quyển",
    "category": ["update ca2", "news"]
}

### Delete article: OK
DELETE http://localhost:5000/api/article/62ef7883501ec117262db2cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDgyNTI5Y2ViYzY3MWNkMDg0Nzk1YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU5ODYxMzc2LCJleHAiOjE2NjA0NjYxNzZ9.sOzGZsf4F0XFgJ-K9uPxYISd84clL95US3xqffLzLZc

# <========= COMMENT ===========>
### Create comment: OK
POST http://localhost:5000/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWZkMzdkZDAyOWJjZDA3YjEwY2Q1YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU5ODg0OTI4LCJleHAiOjE2NjA0ODk3Mjh9.bkxilffLM8trpFFwqNFpdk_rI3ndTd6kn41ZNe3dTb4

{
    "article": "62f000e6b9dbee59f67d2cd4",
    "content": "thang comment"
}


### GET ALL Comment by(userID, artilceID): OK
GET http://localhost:5000/api/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDgyMzFlMjY4ZGE1NTRkZjQ2OWVhMCIsImlhdCI6MTY1OTExOTg4OCwiZXhwIjoxNjU5NzI0Njg4fQ.FH7buIItVbYxppfCGufbNGKfNpW6xGewv119ELGHuEA

# Content-Type: application/json
# ### Get comment by articleId : OK
# GET http://localhost:5000/api/comment/article/62e172d137ad28ca83182265

### Update comment: OK
PUT http://localhost:5000/api/comment/62e4d84ceaa94d01449aad7f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyY2E3OGIxNTdmMWJjMGQ1ZmM2YzY1ZSIsImlhdCI6MTY1OTE2NDU3NCwiZXhwIjoxNjU5NzY5Mzc0fQ.drxsNQhKMUD6AdPE6QS954oYPL5Ia0loTd0II5Yv72Q

{
    "content": "thang3 update thang3 comment"
}

### Delete comment: OK
DELETE http://localhost:5000/api/comment/62e4d84ceaa94d01449aad7f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyY2E3OGIxNTdmMWJjMGQ1ZmM2YzY1ZSIsImlhdCI6MTY1OTE2NDU3NCwiZXhwIjoxNjU5NzY5Mzc0fQ.drxsNQhKMUD6AdPE6QS954oYPL5Ia0loTd0II5Yv72Q

# <========= USER ===========>
### Get all users: OK
GET http://localhost:5000/api/user
//admin token 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDgyMzFlMjY4ZGE1NTRkZjQ2OWVhMCIsImlhdCI6MTY1OTExMzYzOSwiZXhwIjoxNjU5NzE4NDM5fQ.LSHSjdrPT2lLpEGA8ZNPx5n33WHNZpsqmCX7crh7-64

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmQ4MjMxZTI2OGRhNTU0ZGY0NjllYTAiLCJ1c2VyUm9sZSI6ImFkbWluIiwiaWF0IjoxNjU5MDI0MDk0fQ.LRDAFPxqFCuEGSGyyMjSpGikB1iQuOMDsGNIrHHvMr4

### Get user detail: OK
GET http://localhost:5000/api/user/62e16e3c9315b63997745da5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzljOTYxODQ1MTZmNWEyZGE4NTNhYSIsImlhdCI6MTY1OTExOTYxNiwiZXhwIjoxNjU5NzI0NDE2fQ.n6uV7_RUrfXeFmYDZ1uBKZ6h2q-TgFh4Jc8mUd5SSaI

### Update user: OK
PUT http://localhost:5000/api/user/62efd37dd029bcd07b10cd5b
Content-Type: application/json 
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWZkMzdkZDAyOWJjZDA3YjEwY2Q1YiIsImlhdCI6MTY2MDkzMjUwNywiZXhwIjoxNjYxNTM3MzA3fQ.9ZeaLRLH52AK6YQeCTIaCoJZ4l4E1pgywKa2YWVxyK4

{
    "fullname": "Quang Thắng"
}
